branch: master
directory:
- .
download-external-modules: false
evaluate-variables: true
external-modules-download-path: .external_modules
framework:
- all
secrets-scan-file-type: []
skip-check:
- CKV_SECRET_6
- CKV_AZURE_6
- CKV_AZURE_7
- CKV_AZURE_115
- CKV_AZURE_117
- CKV_AZURE_141
-
